"""empty message

Revision ID: 3a41a0cb2b90
Revises: 52e80ec6f5e0
Create Date: 2024-08-30 19:26:54.891584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a41a0cb2b90'
down_revision = '52e80ec6f5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('upper_size', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('lower_size', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('cup_size', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('shoe_size', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('not_colors', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stamps', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('not_clothes', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profession')
        batch_op.drop_column('categories')
        batch_op.drop_column('not_clothes')
        batch_op.drop_column('fit')
        batch_op.drop_column('stamps')
        batch_op.drop_column('not_colors')
        batch_op.drop_column('shoe_size')
        batch_op.drop_column('cup_size')
        batch_op.drop_column('lower_size')
        batch_op.drop_column('upper_size')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
